### ISSUE TITLE
Upstream this

### ISSUE THREAD

**Issue by hoodmane** [hoodmane/libffi-emscripten#16]
We should try to add Emscripten target to upstream libffi.

**Comment by kleisauke** [comment]
Are there any other projects that depends on this fork (besides Pyodide/Python ctypes and the wasm-vips project)?

FYI: there's currently a breaking change in Emscripten that causes a build failure related to this implementation, see: https://github.com/emscripten-core/emscripten/pull/18391#issuecomment-1362734758

**Comment by pmp-p** [comment]
@kleisauke this soft-rt micropython fork uses that ffi for cpython ctypes emulation https://github.com/pmp-p/wapy/tree/wapy-emsdk

**Comment by hoodmane** [comment]
Completed: https://github.com/libffi/libffi/pull/763
